version: "3"
services:

  invidious:
    image: quay.io/invidious/invidious:master-arm64 # ARM64/AArch64 devices
    environment:
      - SERVICE_URL_INVIDIOUS_3000
        # Please read the following file for a comprehensive list of all available
        # configuration options and their associated syntax:
        # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      - INVIDIOUS_CONFIG: |
          db:
            dbname: ${POSTGRES_DB}
            user: ${SERVICE_USER_POSTGRES}
            password: ${SERVICE_PASSWORD_POSTGRES}
            host: invidious-db
            port: 5432
          check_tables: true
          invidious_companion:
          # URL used for the internal communication between invidious and invidious companion
          # There is no need to change that except if Invidious companion does not run on the same docker compose file.
          - private_url: "http://companion:8282"
          # (public) URL used for the communication between your browser and invidious companion
          # IF you are using a reverse proxy OR accessing invidious from an external IP then you NEED to change this value
          # Please consult for more doc: https://github.com/unixfox/invidious/blob/invidious-companion/config/config.example.yml#L57-L88
          # And make sure to add the routes from the post install when using a reverse proxy!
            public_url: "http://localhost:8282"
          # IT is NOT recommended to use the same key as HMAC KEY. Generate a new key!
          # Use the key generated in the 2nd step
          invidious_companion_key: ${SERVICE_REALBASE64_INVIDIOUSCOMPANION}
          external_port: 443
          domain: ${SERVICE_URL_INVIDIOUS}
          https_only: true
          # statistics_enabled: false
          # Use the key generated in the 2nd step
          hmac_key: ${SERVICE_REALBASE64_INVIDIOUS}
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db

  companion:
    image: quay.io/invidious/invidious-companion:latest
    environment:
      - SERVICE_URL_INVIDIOUSCOMPANION_8282
      - SERVER_SECRET_KEY=${SERVICE_REALBASE64_INVIDIOUSCOMPANION}
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    cap_drop:
      - ALL
    read_only: true
    # cache for youtube library
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-invidious}
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
